# Generated by Django 3.1.5 on 2021-01-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('block', models.IntegerField(blank=True, default=None, null=True)),
                ('lot', models.IntegerField()),
                ('principal_phone', models.CharField(max_length=14)),
                ('secondary_phone', models.CharField(blank=True, default=None, max_length=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
