# Generated by Django 3.1.5 on 2021-01-22 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('block', models.IntegerField(blank=True, default=None, null=True)),
                ('lot', models.IntegerField()),
                ('principal_phone', models.CharField(max_length=14)),
                ('secondary_phone', models.CharField(blank=True, default=None, max_length=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('longitude', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('latitude', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('available', models.BooleanField()),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('MANHA', 'morning'), ('TARDE', 'evening'), ('NOITE', 'night')], max_length=5)),
                ('state', models.CharField(choices=[('CONFIRMADO', 'initial'), ('LIVRE', 'free'), ('PENDENTE', 'pending'), ('INDISPONIVEL', 'unavailable'), ('OCUPADO', 'occupied')], max_length=12)),
                ('proprietor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='reservation.proprietor')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cpf', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('reservation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest', to='reservation.reservation')),
            ],
        ),
    ]
